import React from 'react';
import {
  Type,
  RectangleHorizontal,
  Image,
  Sparkles,
  LayoutTemplate,
  Trash2,
  Circle,
  Minus,
  Heart,
  QrCode,
  Eye,
  EyeOff,
  ChevronsUp,
  ChevronsDown,
  AlignHorizontalJustifyStart,
  AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyEnd,
  AlignVerticalJustifyStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  Shapes,
  ChevronDown,
  Link,
  Unlink2,
  Copy,
  CopyPlus,
  ArrowUp,
  ArrowDown,
  Plus,
  AlignHorizontalSpaceBetween,
  AlignVerticalSpaceBetween,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Triangle,
  Star,
  Brush,
  WandSparkles,
  Lock,
  Unlock,
  MousePointer,
  Wand2,
  Eraser,
  // Menu icons
  Undo,
  Redo,
  ClipboardPaste,
  Scissors,
  FileDown,
  FileUp,
  FileImage,
  FileJson2,
  Save,
  // New icons
  Blocks,
  Folder,
  FolderOpen,
  Group,
  Ungroup,
  Printer,
  History,
  Globe,
  UploadCloud,
  Ruler,
  Check,
  Expand as FitToScreenIcon,
  ZoomIn,
  ZoomOut,
  Facebook,
  Instagram,
  Twitter,
  Linkedin,
  Truck,
  ShieldCheck,
  Headset,
  Box,
  Battery,
  Power,
  CheckCircle,
} from 'lucide-react';

export const LCLogoIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
    <svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
      <rect width="100" height="100" rx="20" fill="#4F46E5"/>
      <text x="50" y="55" dominantBaseline="middle" textAnchor="middle" fill="white" fontSize="50" fontFamily="Arial, sans-serif" fontWeight="bold">
        LC
      </text>
    </svg>
);

export const OrientationLandscapeIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <rect x="2" y="6" width="20" height="12" rx="2"></rect>
    </svg>
);

export const OrientationPortraitIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
        <rect x="8" y="2" width="8" height="20" rx="2"></rect>
    </svg>
);


export {
  Type as TextIcon,
  RectangleHorizontal as RectangleIcon,
  Image as ImageIcon,
  Sparkles as SparklesIcon,
  LayoutTemplate as TemplateIcon,
  Trash2 as TrashIcon,
  Circle as CircleIcon,
  Minus as LineIcon,
  Heart as SvgIcon,
  QrCode as QrCodeIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  ChevronsUp as ChevronsUpIcon,
  ChevronsDown as ChevronsDownIcon,
  AlignHorizontalJustifyStart as AlignLeftIcon,
  AlignHorizontalJustifyCenter as AlignCenterHorizontalIcon,
  AlignHorizontalJustifyEnd as AlignRightIcon,
  AlignVerticalJustifyStart as AlignTopIcon,
  AlignVerticalJustifyCenter as AlignCenterVerticalIcon,
  AlignVerticalJustifyEnd as AlignBottomIcon,
  Shapes as ShapesIcon,
  ChevronDown as ChevronDownIcon,
  Link as LinkIcon,
  Unlink2 as UnlinkIcon,
  CopyPlus as DuplicateIcon,
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
  Plus as PlusIcon,
  AlignHorizontalSpaceBetween as DistributeHorizontalIcon,
  AlignVerticalSpaceBetween as DistributeVerticalIcon,
  AlignLeft as TextAlignLeftIcon,
  AlignCenter as TextAlignCenterIcon,
  AlignRight as TextAlignRightIcon,
  AlignJustify as TextAlignJustifyIcon,
  Triangle as TriangleIcon,
  Star as StarIcon,
  Brush as BrushIcon,
  WandSparkles as WandSparklesIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  MousePointer as SelectIcon,
  Wand2 as MagicWandIcon,
  Eraser as EraserIcon,
  // Menu icons
  Undo as UndoIcon,
  Redo as RedoIcon,
  Copy as CopyIcon,
  ClipboardPaste as ClipboardPasteIcon,
  Scissors as ScissorsIcon,
  FileDown as FileDownIcon,
  FileUp as FileUpIcon,
  FileImage as FileImageIcon,
  FileJson2 as FileJsonIcon,
  Save as SaveIcon,
  // New icons
  Blocks as BlocksIcon,
  Folder as FolderIcon,
  FolderOpen as FolderOpenIcon,
  Group as GroupIcon,
  Ungroup as UngroupIcon,
  Printer as PrinterIcon,
  History as HistoryIcon,
  Globe as GlobeIcon,
  UploadCloud as UploadCloudIcon,
  Ruler as RulerIcon,
  Check as CheckIcon,
  FitToScreenIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
  Facebook as FacebookIcon,
  Instagram as InstagramIcon,
  Twitter as TwitterIcon,
  Linkedin as LinkedinIcon,
  Truck as TruckIcon,
  ShieldCheck as ShieldCheckIcon,
  Headset as HeadsetIcon,
  Box as BoxIcon,
  Battery as BatteryIcon,
  Power as PowerIcon,
  CheckCircle as CheckCircleIcon,
};